-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Feb 18, 2016 at 08:09 AM
-- Server version: 5.6.29
-- PHP Version: 5.4.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aseanuni_aseanuni`
--

-- --------------------------------------------------------

--
-- Table structure for table `Uni`
--

CREATE TABLE IF NOT EXISTS `Uni` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `Country` varchar(60) NOT NULL,
  `ArtsAndHumanities` varchar(100) NOT NULL,
  `BusinessAndSocialSciences` varchar(100) NOT NULL,
  `LanguageAndCultural` varchar(100) NOT NULL,
  `MedicineAndHealth` varchar(100) NOT NULL,
  `Engineering` varchar(100) NOT NULL,
  `ScienceAndTechnology` varchar(100) NOT NULL,
  `FlagImage` varchar(60) NOT NULL,
  `About` varchar(1000) NOT NULL,
  `Address` varchar(200) NOT NULL,
  `TelephoneNo.` varchar(30) NOT NULL,
  `Email` varchar(120) NOT NULL,
  `Link` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=47 ;

--
-- Dumping data for table `Uni`
--

INSERT INTO `Uni` (`id`, `name`, `Country`, `ArtsAndHumanities`, `BusinessAndSocialSciences`, `LanguageAndCultural`, `MedicineAndHealth`, `Engineering`, `ScienceAndTechnology`, `FlagImage`, `About`, `Address`, `TelephoneNo.`, `Email`, `Link`) VALUES
(1, 'Institute of Technology of Cambodia', 'Cambodia', '', '', '', '', '', 'Science & Technology', 'cambodia.png', 'Institute of Technology of Cambodia (ITC) is a Cambodian Higher Education Institution which was founded in 1964 and supported by cooperation between the Cambodia and the former Soviet Union. More than 10000 executive members have been graduated from ITC. They are currently working intensely on the economic and social infrastructure development of Cambodia.', 'Russian Federation Boulevard, Sangkat, Toek leak 1, Khan Tuolkok\r\nPhnom Penh\r\nPhnum Pénh\r\nCambodia', '+855 (23) 880 370', 'info@itc.edu.kh', 'http://www.itc.edu.kh/en/'),
(2, 'Royal University of Phnom Penh', 'Cambodia', '', '', 'Language & Cultural', '', '', 'Science & Technology', 'cambodia.png', 'The Royal University of Phnom Penh (RUPP) is Cambodia’s oldest and one of the largest public universities. It hosts more than 12,000 scholarship and full-fee paying students, across a diverse range of undergraduate and postgraduate programs. It is unique in Cambodia for offering specialist degrees in fields including the sciences, humanities and social sciences, as well as professional degrees in fields such as information technology, electronics, psychology, social work, and tourism. RUPP also ', 'Russian Federation Boulevard,\r\nToul Kork, Phnom Penh, Cambodia.', '855-23-883-640', 'secretary@rupp.edu.kh', 'http://www.rupp.edu.kh/'),
(3, 'Stamford International University', 'Thailand', '', 'Business & Social Sciences', 'Language & Cultural', '', '', 'Science & Technology', 'thailand.png', 'Stamford is one of the most diverse universities in Thailand with international students from over 90 countries representing 30% of the student population.\r\n \r\n70% of our faculty members are from overseas including USA, UK, France, Germany and many more.\r\n \r\nExperience a vibrant and interactive international learning environment! At Stamford, every day is a truly cross-cultural experience, with English spoken while socialising as well as learning.', '16, Motorway Road – Km2, Prawet, Bangkok 10250 Thailand.', '+662 769 4000', 'info@stamford.edu', 'http://www.stamford.edu/'),
(4, 'Ateneo de Manila University', 'Philippines', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'philippines.png', 'To understand the soul of the Ateneo de Manila University -- what shaped it and where it came from, where it is going and where it can take you -- it is essential to understand its motto, Lux in Domino, or "Light in the Lord."', 'Katipunan Road, Loyola Heights\r\nQuezon City\r\n1108 National Capital Region\r\nPhilippines', '+63 (2) 426 6001', 'commpr@ateneo.edu', 'http://www.ateneo.edu/'),
(5, 'University of Computer Studies, Yangon', 'Myanmar', '', '', '', '', 'Engineering', 'Science & Technology', 'myanmar.png', 'UCSY''s origins trace back to the founding of the Universities'' Computer Center (UCC) in 1971, located inside the Hlaing Campus of Yangon University. Equipped with ICL Main Frame 1902s, UCC provided computer training to university and government employees.[3] In 1973, it began offering a master''s degree program (MSc in Computer Science), and a graduate diploma program (Diploma in Automated Computing) in cooperation with the Mathematics Department of Yangon University.[4] The center added DEC PDP-11/70 mini-computers in 1983, and personal computers in 1990. In 1986, the center added BSc (Computer Science) and BSc (Computer Technology) degree programs.', 'Hlaing Campus\r\nYangon\r\n11052 Yangon Region\r\nMyanmar', '+95 1 665686', 'info@UCY.edu', 'http://www.ucsy.edu.mm/'),
(6, 'Central Philippine University', 'Philippines', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'philippines.png', 'CENTRAL PHILIPPINE UNIVERSITY is a non-stock, non-profit Christian Institution of higher learning, where a well-rounded program of education is offered under influences that strengthen faith and build up character.\r\n\r\nIt was founded in 1905 as the Jaro Industrial School by missionaries of the American Baptist Foreign Mission Society. It started as an Elementary Vocational School for poor boys who worked for their board and tuition. Perhaps it was the first school in the Philippines to teach that labor is honor. The school also had the distinction of having organized the first student government in the country - the Jaro Industrial School Republic, and one of the oldest student’s newspapers - the Central Echo.', '	\r\nLopez Jaena Street, Jaro\r\nIloilo City\r\n5000 Western Visayas\r\nPhilippines', '+63 (33) 329 1971', 'Email: admin@cpu.edu.ph', 'http://cpu.edu.ph/cpucmsv2/'),
(7, 'National University of Laos', 'Laos', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'laos.png', 'The University of (m g) which was the college full first in the history of Laos was established on November 5, 1996 by a decree of the Prime Minister No. 50 / PM, dated 09/06/1995 , by gather those institutions higher education , which previously belonged to the Ministry as the college uniform.Among such institutions include 10 institutions are: University teacher Vientiane, the university department of December 2, the University of Science Public Health, School of Agriculture Nabong, School of Forestry Dong Dok, School of Irrigation Tad Thong, School of Architecture of the Higher School of Communication and Transport,, careers in high power electronics and connectivity University College of Agriculture - Forest World gold.', 'PO Box 7322\r\nVientiane\r\nViangchan\r\nLaos', '+856 (21) 770 720', 'nuolinfo@nuol.edu.la', 'http://www.nuol.edu.la/'),
(8, 'Nanyang Technological University', 'Singapore', 'Arts & Humanities', 'Business & Social Sciences', '\r\n', 'Medicine & Health', 'Engineering', 'Science & Technology', 'singapore.png', 'Young and research-intensive, Nanyang Technological University (NTU Singapore) is ranked 13th globally. It is also placed 1st amongst the world’s best young universities. \r\n\r\nThe university has colleges of Engineering, Business, Science, Humanities, Arts, & Social Sciences, and an Interdisciplinary Graduate School. It also has a medical school, Lee Kong Chian School of Medicine, set up jointly with Imperial College London.\r\nNTU is also home to world-class autonomous entities such as the National Institute of Education, S Rajaratnam School of International Studies, Earth Observatory of Singapore, and Singapore Centre on Environmental Life Sciences Engineering. \r\nNTU provides a high-quality global education to about 33,000 undergraduate and postgraduate students. The student body includes top scholars and international olympiad medallists from the region and beyond.', 'Nanyang Technological University\r\n50 Nanyang Avenue, Singapore 639798 ', '+(65) 67911744', 'adm_intnl@ntu.edu.sg ', 'http://www.ntu.edu.sg/'),
(9, 'National University of Singapore', 'Singapore', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'singapore.png', 'We started out as a modest medical school in 1905, founded by a determined group of businessmen led by Tan Jiak Kim, to serve the needs of the local community. Today, we are Singapore’s flagship university consistently ranked first in Asia and among the leading universities in the world.', '21 Lower Kent Ridge Road\r\nSingapore 119077', '+65 6516 6666', 'enquiry@nus.edu.sg', 'http://www.nus.edu.sg/'),
(10, 'Singapore Management University', 'Singapore', '', 'Business & Social Sciences', '', '', '', 'Science & Technology', 'singapore.png', 'A premier university in Asia, the Singapore Management University (SMU) is internationally recognised for its world-class research and distinguished teaching. Established in 2000, SMU’s mission is to generate leading-edge research with global impact and produce broad-based, creative and entrepreneurial leaders for the knowledge-based economy. SMU education is known for its highly interactive, collaborative and project-based approach to learning, and for its technologically enabled pedagogy of seminar-style teaching in small class sizes.\r\nHome to around 9,300 undergraduate, postgraduate, executive and professional, full- and part-time students, SMU is comprised of six schools: School of Accountancy, Lee Kong Chian School of Business, School of Economics, School of Information Systems, School of Law, and School of Social Sciences. SMU offers a wide range of bachelors'', masters'' and PhD degree programmes in the disciplinary areas associated with the six schools.', '81 Victoria Street\r\nSingapore 188065', '+65 6828 0100', 'enquiry@smu.edu.sg', 'http://www.smu.edu.sg/'),
(11, 'SIM University', 'Singapore', '', 'Business & Social Sciences', '', '', '', '', 'singapore.png', 'SIM University is a private university in Singapore.[1] It was established in 2005 and is managed separately from the SIM Global Education arm of the Singapore Institute of Management Group.\r\nPreviously, SIM university only admitted part-time students but began to offer publicly funded university places in 2014. Though a private university, eligible students are able to enjoy government tuition fee subsidy, government loans and bursaries for their undergraduate education.[3][4]\r\nAs of 2014 the patron of the university is Tony Tan Keng Yam, President of Singapore. The Chancellor of the university is Professor Cham Tao Soon, who was the founding president of Nanyang Technological University (NTU). The Founding President of SIM University is Professor Cheong Hee Kiat, former deputy president of NTU. In October 2013, it was announced that UniSIM has been selected to house Singapore''s third law school.', '461 Clementi Road\r\nSingapore\r\n599491\r\nSingapore', '+65 6248 0188', 'uc@unisim.edu.sg', 'http://www.unisim.edu.sg/'),
(12, 'Build Bright University', 'Cambodia', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', '', 'Engineering', 'Science & Technology', 'cambodia.png', 'Faculty of Management and Law (FML) was founded in 2000 and situated in the heart of Phnom Penh capital. It has two main teaching buildings known as FML''s Campus in Khan Daunpenh . The distance between each campus is about ten-minute driving. The administrative head office remained on both campuses. The Faculty initially focused its training programs on two specific fields: Management and Law which offered the two-year associate and the four-year bachelor degrees related to both fields. As the number of learners has significantly increased, FML has expanded its training programs. Eventually, it has completely transformed to become a university and took the name as Build Bright University (BBU) in 2002.\r\nThe third and biggest campus, Tonle Basak Campus, has emerged on the most public concentrated area along the Tonle Basac river in Khan Chamkarmon. The university''s head office has then moved to locate on this campus. Today, the three campuses have over 12,000 students enrolled.', 'Brey Building, Samdech Sothearos Bullevards, near Hun Sen Park\r\nPhnom Penh\r\n12301 Phnum Pénh\r\nCambodia', '+855 (23) 987 700', 'info@bbu.edu.kh', 'http://www.bbu.edu.kh/'),
(13, 'Royal University of Agriculture', 'Cambodia', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'cambodia.png', 'Royal University of Agriculture (RUA) is a leading administrative public institution in Cambodia, who plays vital role in educational programs associated with agriculture and related sectors for all levels. RUA was founded in 1964 under the monarch, King Norodom Sihanouk.', 'PO Box 2696, Chamkar Daung\r\nPhnom Penh\r\n12401 Phnum Pénh\r\nCambodia', '+855 (23) 219 829', 'rua@camnet.com.kh', 'http://www.rua.edu.kh/'),
(14, 'Royal University of Law and Economics', 'Cambodia', '', 'Business & Social Sciences', '', '', '', '', 'cambodia.png', 'RULE is the first higher education institution in Cambodia. It was originally found in 1949 as the National Institute of Law, Politics and Economics. 1957 was an important year for the history of the university, the Institute became the Faculty by the Royal Decree. Year 2003 is one of the most important years in the university''s history. The Faculty of Law and Economics was reorganized as a university, under the name of Royal University of Law and Economics RULE).The name of the university still bears the words of Law and Economics (RULE). The name of the university still bears the words of Law and Economics is to indicate that the two disciplines are at the core of the university training program. However, other disciplines of social and natural sciences, such as language and computer sciences are being added in our curriculum. RULE still maintains her position as the premier national university and the leading university in the area of law, economic and business education.', 'Monivong Blvd, District Tonle Basac, Khan Chamkamon, Phnom Penh, CAMBODIA', '+ (855) 12 627 446', 'rector@rule.edu.kh', 'www.rule.edu.kh'),
(15, 'Mahidol University', 'Thailand', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'thailand.png', 'Mahidol University has its origins in the establishment of Siriraj Hospital in 1888 by His Majesty King Chulalongkorn (Rama V), and the hospital''s medical school is the oldest institution of higher learning in Thailand, granting its first medical degree in 1893. Later becoming the University of Medical Sciences in 1943, Mahidol University was renamed with great honor in 1969 by H.M. King Bhumibol Adulyadej , after his Royal Father, H.R.H Prince Mahidol of Songkla , who is widely known as the ''Father of Modern Medicine and Public Health in Thailand''. Mahidol University has since developed into one of the most prestigious universities in Thailand, internationally known and recognized for the high caliber of research and teaching by its faculty, and its outstanding achievements in teaching, research, international academic collaboration and professional services.', '999 Phuttamonthon 4 Road, Salaya, Nakhon Pathom 73170 \r\nThailand', '+66 2849 6000', 'opinter@mahidol.ac.th', 'https://www.mahidol.ac.th'),
(16, 'Chulalongkorn University', 'Thailand', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'thailand.png', 'Chulalongkorn University is Thailand ’s first institution of higher education founded nearly a century ago. As a national intellectual center, the university produces the highest quality graduates with a high level of knowledge and skills in the arts and sciences that they can use to contribute to society.\r\nFor more than 90 years now, Chulalongkorn has been committed to ongoing development in programs, human resources, facilities and services. With the cooperation of alumni, we have been building an intellectual community devoted to serving Thai society and the nation. During national disasters and turmoil, Chulalongkorn continues to serve as a central pillar for finding the solutions and assistance to solve these problems.\r\nChulalongkorn University should not be thought of as just an honored institution of learning but as a caring home. We are determined to graduate not just the best qualified but persons of integrity under the credo, “The Pride of Chula is in Serving the Public”', '254 Phayathai Road, Pathumwan, Bangkok Thailand. 10330', '+662-215-0871-3', 'int.off@chula.ac.th', 'http://www.chula.ac.th/'),
(17, 'Assumption University', 'Thailand', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'thailand.png', 'Assumption University has been providing education to the youth of the Thai and other nations since 1969. The University employs English as the official medium of instruction and has formal links and cooperation agreements with a large network of international institutions of higher learning for scholastic exchange and research programs. The University is administered by the Montfort Brothers of St. Gabriel, a worldwide Catholic Religious Order devoted to education and philanthropic activities. The Congregation operates 15 educational institutions in Thailand.', '592/3 Ramkhamhaeng 24 Road, Hua Mak\r\nBangkok\r\n10240 Bangkok Metropolitan Area\r\nThailand', '+66 (2) 300 4553 62', 'info@au.edu', 'http://www.au.edu'),
(18, 'Asian Institute of Technology', 'Thailand', '', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'thailand.png', 'The Asian Institute of Technology promotes technological change and sustainable development in the Asian-Pacific region through higher education, research and outreach. Established in Bangkok in 1959, AIT has become a leading regional postgraduate institution and is actively working with public and private sector partners throughout the region and with some of the top universities in the world.\r\nRecognized for its multinational, multicultural ethos, the Institute operates as a self-contained international community at its campus located 40km (25 miles) north of downtown Bangkok, Thailand.\r\n\r\nBesides the usual labs and academic buildings, the main campus includes housing, sports, and medical facilities, a conference center, and a library with over 230,000 volumes and 830 print and on-line periodicals.', '58 Moo 9, Km. 42, Paholyothin Highway\r\nKlong Luang, Pathumthani 12120\r\nThailand', '+(66 2) 524 5000', 'Admissions@ait.ac.th', 'http://www.ait.ac.th/'),
(19, 'Singapore University of Technology and Design', 'Singapore', 'Arts & Humanities', '', '', '', 'Engineering', 'Science & Technology', 'singapore.png', 'The Singapore University of Technology and Design (SUTD) education is one that is interdisciplinary, with a good grounding in science, technology, arts, humanities and social sciences. Design as a discipline, cuts across the curriculum and provides a novel framework for the research and educational programme. The curriculum is taught through a unique pedagogy – one which starts with students organized around small group learning communities that will provide more intimate connections with faculty and one another.\r\n\r\nAt SUTD, students are also provided with flexible options; they do not choose their focus areas (pillars) until after one and a half years of common curriculum. This provides students with the opportunity to explore various subjects before making informed decisions about their focus areas.\r\n\r\nLearning at SUTD is exciting as well as hands-on. SUTD students will engage in project-based hands-on learning throughout their curriculum.', '8 Somapah Road \r\nSingapore 487372', ' +65 6303 6600', 'enquiry@sutd.edu.sg', 'http://www.sutd.edu.sg/'),
(20, 'University of the Philippines Diliman', 'Philippines', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'philippines.png', 'The University of the Philippines Diliman (UPD) is the biggest campus and the physical seat of the UP System (UPS) Administration.\r\nUPD was formally established as an autonomous unit at the 976th meeting of the Board of Regents (BOR) on April 23, 1985. To date, it is the largest constituent university (CU) in terms of the number of\r\ndegree-granting academic units, student population, faculty and library resources.\r\nUPD occupies 493 hectares of prime land in Quezon City, offering a comprehensive array of disciplines in the baccalaureate and post-baccalaureate levels. In 2013, UPD had 27 degree-granting units on campus offering academic programs in 376 major fields, with 72 programs at the doctoral level, 164 at the master’s and 140 at the undergraduate levels. In addition to the units in the main campus, UPD has extension programs in Pampanga and Olongapo City.', 'Diliman\r\nQuezon City\r\n1101 National Capital Region\r\nPhilippines', '+63 (2) 928 0110', 'updio@upd.edu.ph', 'http://upd.edu.ph/'),
(21, 'De La Salle University', 'Philippines', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', '', 'Engineering', 'Science & Technology', 'philippines.png', 'De La Salle University positions itself as a leader in molding human resources who serve the church and the nation. It is a Catholic coeducational institution founded in 1911 by the Brothers of the Christian Schools. The University is a hub for higher education training renowned for its academic excellence, prolific and relevant research, and involved community service.\r\nNestled in the heart of Manila, De La Salle University is home to local and international students seeking quality education for a brighter future ahead. It is situated in a vibrant city where culture and diversity is well manifested.', '2401 Taft Avenue, \r\n1004 Manila, \r\nPhilippines', '+63 (2) 524 4611', 'registrar@dlsu.edu.ph', 'http://www.dlsu.edu.ph/'),
(22, 'University of the Philippines System', 'Philippines', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'philippines.png', 'The University of the Philippines was founded on June 18, 1908 through Act No. 1870 of the Philippine Assembly. The UP was the result of the Secretary of Public Instruction, W. Morgan Schuster’s recommendation to the Philippine Commission, the upper house of the Philippine Assembly. Act 1870 authorized the Governor General to establish the University of the Philippines in the “city of Manila, or at any point he may deem most convenient.” The UP was to give “advanced instruction in literature, philosophy, the sciences and arts, and to give professional and technical training” to every qualified student regardless of “age, sex, nationality, religious belief and political affiliation.”', 'Main Adm. Bldg: UPD, Quezon Hall\r\nQuezon City\r\n1101 National Capital Region\r\nPhilippines', '+63 (2) 981 8500', 'upsio@upd.edu.ph', 'http://www.up.edu.ph/'),
(23, 'University of Medicine 1, Yangon', 'Myanmar', '', '', '', 'Medicine & Health', '', '', 'myanmar.png', 'The history of the University of Medicine (1) began with the establishment of the Government Medical School in Myanmar in 1907 at the premises of the old Rangoon General Hospital, and the introduction of a course in medical sciences. It was a four-year medical course known as Licentiate in Medical Practice (L.M.P.) course, and the successful candidate was offered a certificate of license for medical practice. In 1923-24, the Bachelor of Medicine and Bachelor of Surgery (MB, B.S.) course was introduced at the old Rangoon College building at the site of the present Neurology Department of the Yangon General Hospital. Academic matters and general administration were attended to by the principal with the help of the Medical College Council (Academic Body). In 1937 the medical {MB, B.S. (Rgn)} degree conferred by the University of Rangoon gained recognition of the General Medical Council of Great Britain.', 'No.245, Myoma Kyaung Street, Lanmadaw Township, Yangon, Myanmar.', '+095 - 251032', 'imy03@imy.net.mm', 'http://www.um1ygn.edu.mm/'),
(24, 'Mandalay University', 'Myanmar', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', '', '', '', 'myanmar.png', 'In June 1925, Mandalay College was founded on  the campus of 253.3316 acres as an affiliatedinstitution to the University of Rangoon  (University of Yangon).\r\nIn 1947, it was upgraded to a degree college and named Mandalay University College.\r\nIn 1958 , it became the University of Mandalayand there were faculties of Arts, Science,Agriculture and Medicine.\r\nIn 1964 the faculties of Agriculture and Medicine were carved out from UM to become separate Universities.\r\nSince then, it was called The University of Mandalay.', '41st St, \r\nMandalay, \r\nMyanmar (Burma)\r\n', '+95 943062273', 'thida09@gmail.com', 'http://www.mu.edu.mm/'),
(25, 'University of Nursing, Mandalay', 'Myanmar', '', '', '', 'Medicine & Health', '', '', 'myanmar.png', 'Nursing education in Mandalay started since 1958 as a nursing and midwifery training school located within the campus of Mandalay General Hospital. It was three years training course conferred a diploma in nursing and midwifery certificate under the guidance and supervision of Institute of Medicine, Mandalay. The rector of the medical institute took responsibility for administrative aspects of the training school whereas principal took responsibility for academic matters.', 'Nursing University, \r\n63rd Street, \r\nMandalay.', '+95-2-80404', ' rectoruonmdy@gmail.com', 'http://uonmdy.gov.mm/'),
(26, 'Yangon Technological University', 'Myanmar', '', '', '', '', 'Engineering', 'Science & Technology', 'myanmar.png', 'Yangon Technological University (YTU) located in Gyogone, Yangon, is the premier engineering university of Myanmar. Established as Department of Engineering under Rangoon University in 1924,[2] and popular known by its former name RIT (Rangoon Institute of Technology), YTU is the country''s oldest and largest engineering university, and the best engineering university in Myanmar. The university offers bachelor''s, master''s and doctorate degree programs in engineering disciplines to nearly 8000 students.', 'Yangon Technological University,\r\nGyogone, Insein Township, \r\nYangon', '+95 1-651717', 'icseoffice@gmail.com', 'http://ytu.edu.mm/'),
(27, 'Institut Teknologi Bandung', 'Indonesia', 'Arts & Humanities', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'indonesia.png', 'Institut Teknologi Bandung (ITB) or Bandung Insitute of Technology or Institute of technology Bandung, was founded on March 2, 1959. The present ITB main campus is the site of earlier engineering schools in Indonesia. Although these institutions of higher learning had their own individual characteristics and missions, they left influence on developments leading to the establishment of ITB.', 'Jalan Ganesha 10\r\nBandung\r\n40116 West Java\r\nIndonesia', '+62 (22) 423 1792', 'iro@itb.ac.id', 'http://www.itb.ac.id/'),
(28, 'Universitas Gadjah Mada', 'Indonesia', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'indonesia.png', 'Universitas Gadjah Mada (internationally known as Gadjah Mada University ; Abbreviation : UGM) is an Indonesian public ivy league research university located in Yogyakarta, Indonesia, founded on December 19, 1949. UGM is the oldest and largest institution of higher learning in Indonesia. Located in Yogyakarta, Indonesia, the 360 acre university comprises of 18 faculties, 68 undergraduate study programs,  23 diploma study programs, 104 master and spesialist study program, and 43 Doctorate  study programs. It has approximately 55,000 students, 1,187 foreign students and 2,500 faculty members currently. Universitas Gadjah Mada has been considered to be one of the most prestigious universities in Indonesia.', 'Kampus Bulaksumur\r\nYogyakarta\r\n55281 Special Region of Yogyakarta\r\nIndonesia', '+62 (274) 588 688', 'humas@ugm.ac.id', 'http://ugm.ac.id/'),
(29, 'Universitas Indonesia', 'Indonesia', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'indonesia.png', 'Universitas Indonesia is a modern, comprehensive, open-minded, multi-culture, and humanism campus that covers wide arrays of scientific disciplines.\r\nUI simultaneously strives to be one of the leading research universities and the most outstanding academic institution in the world. UI is distinctive among research universities in its commitment to the academic invention and research activities through various scientific programs.\r\nUI was founded in 1849 and represents the most experiencing educational institution in Asia.\r\nRecently, UI produces more than 400.000 alumni and continues its important role both nationally and internationally. Furthermore, it is our commitment to produce high quality of education system, global standard research activities and maintaining high standard of international academic research publications.', 'Kampus Baru UI Depok\r\nDepok 16424\r\nIndonesia', '+62 21 786 7222', 'humas-ui@ui.ac.id', 'http://www.ui.ac.id/'),
(30, 'Universitas Sebelas Maret', 'Indonesia', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'indonesia.png', 'Sebelas Maret University was established on March 11, 1976. It was named Universitas Negeri Surakarta (State University of Surakarta), hence was abbreviated UNS. Sebelas Maret University is the result of the unification of the five universities in Surakarta, which were:\r\nInstitute of Teacher Training and Education of Surakarta.\r\nSports High School of Surakarta.\r\nAcademy of Business Administration of Surakarta.\r\nCombined University of Surakarta, which comprised several universities in Surakarta, included University of Islam Indonesia of Surakarta.\r\nFaculty of Medicine of the Department of Defense and Security''s National Higher Education Development of Surakarta.\r\nPhysical development began in 1980. Under the leadership of dr. Prakosa, the original campus located in several places were united in the same area. The new area was in Kentingan, on the riverside of Bengawan Solo River, with an area of 60 hectares. In this Kentingan area, the first phase of campus construction ended in 1985.', 'Jalan Ir. Sutami 36A\r\nSurakarta\r\n57126 Central Java\r\nIndonesia', '+62 (271) 646 994', 'puskom@uns.ac.id', 'https://uns.ac.id'),
(31, 'Universiti Malaya', 'Malaysia', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', 'Medicine & Health', 'Engineering', 'Science & Technology', 'malaysia.png', 'University of Malaya, or UM, Malaysia''s oldest university, is situated on a 750 acre (309 hectare) campus in the southwest of Kuala Lumpur, the capital of Malaysia.\r\n\r\nIt was established on 8th October 1949 in Singapore with the merger of the King Edward VII College of Medicine (founded in 1905) and Raffles College (founded in 1928).\r\n\r\nThe University of Malaya derives its name from the term ''Malaya'' as the country was then known. The Carr-Saunders Commission on University Education in Malaya, which recommended the setting up of the university, noted in its Report in 1948: "The University of Malaya would provide for the first time a common centre where varieties of race, religion and economic interest could mingle in joint endeavour ... For a University of Malaya must inevitably realise that it is a university for Malaya."', 'Pantai Valley\r\nKuala Lumpur\r\n50603 Selangor\r\nMalaysia', '+60 (3) 7967 7022', 'icr@um.edu.my', 'http://www.um.edu.my/'),
(32, 'Universiti Sains Malaysia', 'Malaysia', '', '', '', '', '', 'Science & Technology', 'malaysia.png', 'Background of Institution\r\nEstablished as the second university in the country in 1969, Universiti Sains Malaysia (USM) was first known as Universiti Pulau Pinang. In 1971, USM moved from its temporary premises at the Malayan Teachers’ Training College, Bukit Gelugor to the present 416.6 hectare site at Minden, approximately 9.7 km from Georgetown.\r\nUSM offers courses ranging from Natural Sciences, Applied Sciences, Medical and Health Sciences, Pharmaceutical Sciences to Building Science and Technology, Social Sciences, Humanities, and Education. These are available at undergraduate and postgraduate levels to approximately 30,000 students at its 17 Academic Schools on the main campus in the island of Penang; 6 Schools at the Engineering Campus in Nibong Tebal (approximately 50km from the main campus); and 3 at the Health Campus in Kubang Kerian, Kelantan (approximately 300km from the main campus).', 'Jalan Sungai Dua\r\nGeorgetown\r\n11800 Pulau Penang\r\nMalaysia', '+60 (4) 653 3888', 'info@usm.my', 'https://www.usm.my/'),
(33, 'Universitas Negeri Yogyakarta', 'Indonesia', 'Arts & Humanities', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'indonesia.png', 'Yogyakarta State University (formerly IKIP Yogyakarta or Yogyakarta Institute of Teacher Education and Educational Sciences) was founded on May 21, 1964. Historically, IKIP Yogyakarta was a merger of two educational institutions: the Faculty of Pedagogy of Gadjah Mada University and the Institute of Teacher Education. These two institutions offered study programs of educational sciences and teacher education. The merger itself was mandated by the Presidential Decree of the Republic of Indonesia.', 'Karangmalang\r\nYogyakarta\r\n55281 Special Region of Yogyakarta\r\nIndonesia', '+62 (274) 586 168', 'international.office@uny.ac.id', 'http://english.uny.ac.id/'),
(34, 'Universiti Teknologi Malaysia', 'Malaysia', '', '', '', 'Medicine & Health', '', 'Science & Technology', 'malaysia.png', 'The history of technical education in this country has been a century old. It all began in 1904 when a Technical School began its operation on Weld Road (now Jalan Raja Chulan) to teach Technical Assistants for the Federated Malay States Departments of Railways, Survey and Public Works.\r\n\r\nThe school was officially known as Treacher Technical School, named after Sir William Treacher, the Resident General during that time. Students followed classed on part-time basis; they worked and trained specifically according to the technical needs of their employment.', 'Skudai, Locked Bag 791\r\nJohor Bahru\r\n81310 Johor\r\nMalaysia', '+60 (7) 553 0692', 'upa@utm.my', 'http://www.utm.my'),
(35, 'Vietnam National University, Hanoi', 'Vietnam', 'Arts & Humanities', 'Arts & Humanities', 'Language & Cultural', '', 'Engineering', 'Science & Technology', 'vietnam.png', 'As the first modern university established and one of the two national universities in Vietnam, VNU has undergone various stages of development: the University of Indochina established on 16 May, 1906; Vietnam National University (November, 1945); the University of Hanoi (June, 1956). In December 1993, VNU was reorganized on the basis of amalgamating the University of Hanoi and some other leading universities in Hanoi.\r\nVNU is the largest comprehensive higher education and research center in Vietnam. VNU is entrusted with the task of producing highly qualified human resources and talents for the industrialization and modernization of the country.', '144 Xuan Thuy Street, Cau Giay District\r\nHanoi\r\n10000 Hanoi\r\nVietnam', '+84 (4) 3754 9042', ' lttthuy@vnu.edu.vn', 'https://vnu.edu.vn/eng/'),
(36, 'Can Tho University', 'Vietnam', 'Arts & Humanities', 'Business & Social Sciences', 'Language & Cultural', '', 'Engineering', 'Science & Technology', 'vietnam.png', 'Established in 1966, Can Tho University (CTU) is widely recognized as a premier university in the Mekong Delta of Vietnam. Its goal is to strengthen its reputation within Vietnam and join the ranks of internationally renowned universities. Accordingly, it is committed to constantly improving its capacity in training, scientific research, technology transfer, and services. As one of Vietnam leading multidisciplinary universities located in the heart of the Mekong Delta, CTU enjoys a special niche among higher education institutions in Vietnam. Currently, the University has around 2.000 staff members and almost 57.000 students, and offers nearly 100 undergraduate, 36 Master and 15 Doctoral training programs in a wide range of majors.', '3/2 Street, Xuan Khanh Ward, Ninh Kieu District\r\nCan Tho\r\n92000 Cantho\r\nVietnam', '+84 (710) 383 2663', 'dhct@ctu.edu.vn', 'http://www.ctu.edu.vn/en/'),
(37, 'Universiti Teknologi MARA', 'Malaysia', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'malaysia.png', 'Universiti Teknologi MARA August 26, 1999\r\nIn August 1999, the then Prime Minister of Malaysia, YAB Dato'' Seri Dr Mahathir Mohamad announced the change in name of ITM to Universiti Teknologi MARA (UiTM). With such acknowledgement from the government, a major restructuring exercise was carried out in order to consolidate the University''s resources for optimum productivity.\r\n\r\nUiTM aspires to be world class in all its endeavours and forges ahead in a direction that is in tandem with the latest developments in the world. As UiTM moves forward, it remains focused on academic excellence, innovation, socio-economic goals, worldwide accreditation, globalisation and new technologies in order to contribute to industry and national development.', '	\r\nShah Alam\r\n40450 Selangor\r\nMalaysia', '+60 (3) 5544 2000', 'info@uitm.my', 'http://www.uitm.edu.my'),
(38, 'Ho Chi Minh City University of Technology', 'Vietnam', '', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'vietnam.png', 'Ho Chi Minh City University of Technology (HCMUT) was established in 1957 and has been recognized as a center of excellence among technological universities in Vietnam. Prior to the country re-unification in 1975, the university was the only institution to produce engineers in the Southern Vietnam. Up to the present day, HCMUT still remains as the largest, the most prestigious and the oldest engineering university in the South of Vietnam. The University has two campuses: one is located in the inner of Ho Chi Minh City and the other in the outskirts of the city. Located in a metropolitan area about 4km from downtown Ho Chi Minh City and nearly 3km from the international airport, the former one sets on a 14.5-hectare campus full of greenery. The latter one, with an area of 26 hectares, is located about 28 km from the city campus. HCMUT has 26750 students enrolled in 11 academic faculties and 1300 full-time staff members.', '	\r\n268 Ly Thuong Kiet Street, District 10\r\nHo Chi Minh City\r\nHo Chi Minh\r\nVietnam', '+84 (8) 38 647 256', ' inter@hcmut.edu.vn', 'http://www.hcmut.edu.vn/'),
(39, 'Universiti Tenaga Nasional', 'Malaysia', '', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'malaysia.png', 'The objective of the College of Foundation and General Studies is to prepare the pathway for students into the various bachelors degree programmes offered in the university. Since June 2003, Universiti Tenaga Nasional has been accepting applicants with the Sijil Pelajaran Malaysia (SPM) qualification or its equivalent, into a one-year Foundation programme. Students who complete the Foundation programme successfully will be able to pursue further studies in the appropriate Degree (Honours) programmes. The Foundation programmes provide a comprehensive and proper coverage of disciplines that equips students for entrance into UNITEN, and also other universities in Malaysia.\r\nIn addition, these foundation studies will also train students to be confident entrepreneurs and future leaders, and present them with lots of opportunities to experience a well-balanced and holistic education in our college. Come and join us, and we will help you succeed in finding your place in the university.', 'Jalan Ikram-Uniten\r\nKajang\r\n43000 Selangor\r\nMalaysia', '+60 (3) 8921 2020', 'info@uniten.edu.my', 'www.uniten.edu.my/'),
(40, 'Hanoi University of Science and Technology', 'Vietnam', '', 'Business & Social Sciences\r\n', '', '', 'Engineering', 'Science & Technology', 'vietnam.png', 'Hanoi University of Science and Technology (HUST) was established in 1956. Over  half century, HUST has been continuously growing and making considerable contributions to the industrialization and modernization process of the country. A large number of scientists and highly qualified engineers, who obtained various academic degrees of Eng., MSc. And PhD. at HUST, have been working effectively in various political, cultural and social fields and science & technology development throughout the country. The obvious achievements in training and research undertaken at HUST and their application to production activities, have contributed significantly to flourishing national technologies.', 'No. 1, Dai Co Viêt\r\nHa Noi\r\nHanoi\r\nVietnam', '+84 (4) 869 3796', 'info@hurst.edu.vt', 'http://en.hust.edu.vn/'),
(41, 'Universiti Brunei Darussalam', 'Brunei', 'Arts & Humanities', 'Business & Social Sciences', '', 'Medicine & Health', 'Engineering', 'Science & Technology', 'brunei.png', 'The Universiti Brunei Darussalam is emerging as one of the leading institutions of higher education in Asia. It was established in 1985, opening its doors to the first intake of 176 students. Since then, UBD has seen an increase in the number of graduates, the introduction of new academic programmes, the enhancement of infrastructure and the development of graduate studies.\r\nThe Universiti Brunei Darussalam is guided by its four core values? people, expertise, relevance and leadership. These values are used as yardsticks in the development and running of eight academic faculties, nine research institutes and six academic service centres ranging from Islamic Studies, Business, Arts, Science, Health Sciences, Asian Studies, Policy Studies, Education, Biodiversity and Integrated Technologies.', 'Jalan Tungku Link\r\nGadong\r\nBE1410 Brunei and Muara\r\nBrunei', '+673 246 3001', 'office.recruit@ubd.edu.bn', 'www.ubd.edu.bn/'),
(42, 'Foreign Trade University', 'Vietnam', '', 'Business & Social Sciences', '', '', '', '', 'vietnam.png', 'Foreign Trade University, or FTU, is a university established in 1960, located in Hanoi, Vietnam. FTU is among the most well-known universities in Vietnam, covering a wide range of business courses among which are finance, management, and marketing. The annual admissions test to the university is the most competitive in Vietnam. Students from FTU are recognized as being active and well-qualified. The university also has campuses in Ho Chi Minh City and H? Long - Qu?ng Ninh. It has both undergraduate and graduate programs for foreign students. These courses are taught in Vietnamese, English, and French. In the fall semester 2012, the FTU welcomed undergraduate exchange students from the US, Norway, Sweden, Germany, Switzerland, France, Spain, Japan and South Korea, who stayed mostly for one semester but in parts also for two. Besides student exchanges as a part of an academic partnership, the FTU also allows self-organized exchange semesters (commonly known as "Free Mover" semesters).', '91 Chua Lang, Dong Da\r\nHa Noi\r\nHanoi\r\nVietnam', '+84 (4) 3259 5168', 'info@FTU.edu.vn', 'http://english.ftu.edu.vn/'),
(43, 'Universiti Islam Sultan Sharif Ali', 'Brunei', '', 'Business & Social Sciences', 'Language & Cultural', '', '', '', 'brunei.png', 'Universiti Islam Sultan Sharif Ali - better known as UNISSA - is a "pure Islamic University" of international standard that offers a variety of programs across disciplines based on Al-Quran and al-Sunnah. Established in 2007, it attests to the commitment of His Majesty the Sultan and Yang Di-Pertuan of Brunei Darussalam in upholding Islam through education, in this blessed land of Brunei Darussalam and towards the development of the ummah in general.\r\nAs the second state university, UNISSA strives to produce Muslim scholars and intellectuals who contribute to the development of the ummah and the state, in support of the efforts of Brunei Darussalam towards becoming a Zikir nation with continuous blessings from Allah.', 'Jalan Tungku\r\nGadong\r\nBE1410 Brunei and Muara\r\nBrunei', '+673 246 2000', 'info@unissa.edu.bn', 'http://www.unissa.edu.bn/en/'),
(44, 'Institut Teknologi Brunei', 'Brunei', '', '', '', '', '', 'Science & Technology', 'brunei.png', 'Institut Teknologi Brunei (ITB) was set up in January 1986 with the primary objective of catering for a range of interests in technical and commercial education. Its establishment was supported by Leeds Polytechnic, United Kingdom (now known as Leeds Metropolitan University) which indicates ITB’s aspiration to become a local institution that strives for international recognition.\r\n\r\nThree Departments were first established in a shared campus with Sultan Saiful Rijal Technical College: namely Business and Management (BM), Computer and Information Systems (CIS) and Electrical and Electronic Engineering (EEE). EEE was renamed as Electrical and Communication Engineering (ECE) when ITB moves to its permanent campus. The Phase 1 of ITB permanent campus in ‘Kampung Tungku’ was completed in 1998 with an establishment of two more departments, namely Civil and Mechanical Engineering.', '	\r\nJalan Tungku Link\r\nGadong\r\nBE1410 Brunei and Muara\r\nBrunei', '+673 246 1020', 'enquiry@itb.edu.bn', 'http://www.itb.edu.bn/'),
(45, 'Politeknik Brunei', 'Brunei', 'Arts & Humanities', 'Business & Social Sciences', '', '', 'Engineering', 'Science & Technology', 'brunei.png', 'Consent for the establishment of a polytechnic in Brunei Darussalam was given by His Majesty the Sultan and Yang Di-Pertuan of Brunei Darussalam in his Decree during the National Teachers’ Day Celebration on 18 October 2008.\r\n \r\nIn January 2012, Politeknik Brunei opened its doors and began operation as the first polytechnic in Brunei Darussalam by offering a total of 9 Advanced Diploma (AD) programmes with a total of 401 students being enrolled. Currently, a total of 11 AD programmes are being offered by the institution in its temporary campus at Jalan Ong Sum Ping, Bandar Seri Begawan.', 'Block 2E, Ong Sum Ping Condominium, Jalan Ong Sum Ping\r\nBandar Seri Begawan\r\nBA1311 Brunei and Muara\r\nBrunei', '+673 223 4466', 'contact@pb.edu.bn', 'http://www.pb.edu.bn/'),
(46, 'Institut Pendidikan Teknikal Brunei', 'Brunei', '', '', '', '', '', 'Science & Technology', 'brunei.png', 'The mission of IBTE CET is to provide more opportunities in non-formal and informal education and skills training for the public. IBTE CET is committed to a proactive and evidence-based approach that continually assesses and responds to school leavers, working adults, community and employer demand for upgrading both academic and skills training.\r\nThe Continuing Education and Training (CET) under the Institute of Brunei Technical Education has been in existence since 1958. The IBTE CET short courses, programs and workshops are designed to meet your needs. We are committed to providing quality, innovative training and personal enrichment opportunities for the citizens and non-citizens of Brunei Darussalam. The IBTE CET provides lifelong learning opportunities which allow adult learners to acquire further knowledge and skills in relevant fields.', 'Simpang 347, Jalan Pasar Baharu, Gadong\r\nBandar Seri Begawan\r\nBE1310 Brunei and Muara\r\nBrunei', '+673 242 5555', 'info@ibte.edu.bn', 'https://ibte.edu.bn/');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
